In [53]:
#import pkgs
import numpy as np
import pandas as pd
from scipy import stats

In [54]:
#import f1 and fpr results from models
%store -r f1_svm_case1
%store -r fpr_svm_case1

%store -r f1_svm_case2
%store -r fpr_svm_case2

%store -r f1_svm_case3
%store -r fpr_svm_case3

In [55]:
#import f1 and fpr results from models
%store -r f1_nb_case1
%store -r fpr_nb_case1

%store -r f1_nb_case2
%store -r fpr_nb_case2

%store -r f1_nb_case3
%store -r fpr_nb_case3

In [56]:
#import f1 and fpr results from models
%store -r f1_knn_case1
%store -r fpr_knn_case1

%store -r f1_knn_case2
%store -r fpr_knn_case2

%store -r f1_knn_case3
%store -r fpr_knn_case3

In [57]:
#run kruskal-wallis test
res_c1 = stats.kruskal(f1_svm_case1, f1_nb_case1, f1_knn_case1)
res_c1_fpr = stats.kruskal(fpr_svm_case1, fpr_nb_case1, fpr_knn_case1)

#store both results in one list
res_case1_comb = list(res_c1) + list(res_c1_fpr)

#run kruskal-wallis test
res_c2 = stats.kruskal(f1_svm_case2, f1_nb_case2, f1_knn_case2)
res_c2_fpr = stats.kruskal(fpr_svm_case2, fpr_nb_case2, fpr_knn_case2)

#store both results in one list
res_case2_comb = list(res_c2) + list(res_c2_fpr)

#run kruskal-wallis test
res_c3 = stats.kruskal(f1_svm_case3, f1_nb_case3, f1_knn_case3)
res_c3_fpr = stats.kruskal(fpr_svm_case3, fpr_nb_case3, fpr_knn_case3)

#store both results in one list
res_case3_comb = list(res_c3) + list(res_c3_fpr)

In [58]:
#store dataframe labels
labels_sum = ['Statistic', 'Case 1', 'Case 2', 'Case 3']
ylabels = ['F1 H Statistic', 'F1 p Value', 'FPR H Statistic', 'FPR p Value'] 

#fill dataframe with results
res_krus = pd.DataFrame(columns = labels_sum)
res_krus['Statistic'] = ylabels
res_krus['Case 1'] = res_case1_comb
res_krus['Case 2'] = res_case2_comb
res_krus['Case 3'] = res_case3_comb

#check dataframe
res_krus

         Statistic     Case 1     Case 2     Case 3
0   F1 H Statistic  19.939920  20.387097  20.015484
1       F1 p Value   0.000047   0.000037   0.000045
2  FPR H Statistic  20.051363  17.006892  18.996373
3      FPR p Value   0.000044   0.000203   0.000075

In [59]:
#run kruskal-wallis test
res_c1_r1 = stats.kruskal(f1_svm_case1, f1_nb_case1)
res_c1_fpr_r1 = stats.kruskal(fpr_svm_case1, fpr_nb_case1)

#store both results in one list
res_case1_comb_r1 = list(res_c1_r1) + list(res_c1_fpr_r1)

#run kruskal-wallis test
res_c2_r1 = stats.kruskal(f1_svm_case2, f1_nb_case2)
res_c2_fpr_r1 = stats.kruskal(fpr_svm_case2, fpr_nb_case2)

#store both results in one list
res_case2_comb_r1 = list(res_c2_r1) + list(res_c2_fpr_r1)

#run kruskal-wallis test
res_c3_r1 = stats.kruskal(f1_svm_case3, f1_nb_case3)
res_c3_fpr_r1 = stats.kruskal(fpr_svm_case3, fpr_nb_case3)

#store both results in one list
res_case3_comb_r1 = list(res_c3_r1) + list(res_c3_fpr_r1)

In [60]:
#store dataframe labels
labels_sum = ['Statistic', 'Case 1', 'Case 2', 'Case 3']
ylabels = ['F1 H Statistic', 'F1 p Value', 'FPR H Statistic', 'FPR p Value'] 

#fill dataframe with results
res_krus = pd.DataFrame(columns = labels_sum)
res_krus['Statistic'] = ylabels
res_krus['Case 1'] = res_case1_comb_r1
res_krus['Case 2'] = res_case2_comb_r1
res_krus['Case 3'] = res_case3_comb_r1

#check dataframe
res_krus

         Statistic     Case 1     Case 2     Case 3
0   F1 H Statistic   1.286682   2.285714   1.462857
1       F1 p Value   0.256660   0.130570   0.226476
2  FPR H Statistic  11.297015  12.088273  14.503817
3      FPR p Value   0.000776   0.000507   0.000140